CLOUD_NAME=prod147077.m-yqb-c1.int.ipaas.test.automation.ibm.com
LOGIN_URL=idm-az-us.softwareag-stage.cloud
TENANT_NAME=prod147077
PROJECT_NAME=PerformanceTest
REMOTE_EDGE_SERVER_NAME=edgeorigin
PRODUCT_BUILD=ORIGIN_12.0.3.0
BASELINE_VERSION=12.0
TEST_CASE_FILE=Tests/Benchmark_testcase_All.csv
JMETER_HOME=/opt/apache-jmeter-5.6.3/
#CHANGE THE TEST MASTER KEY BASED ON THE HYPERSCALER
#For AWS - ORIGIN_AWS_BPT
#For AZURE - ORIGIN_AZURE_BPT
TEST_MASTER_KEY=ORIGIN_AZURE_BPT
#DO NOT CHANGE BELOW LINE
RUN_ID=RUN_ID_VALUE
