CLOUD_NAME=originawsdev1.dev-int-aws-us.webmethods.io
LOGIN_URL=idm-aw-us.softwareag-stage.cloud
TENANT_NAME=originawsdev1
TENANT_USERNAME=wmio
TENANT_PASSWORD=Test@1234
PROJECT_NAME=PerformanceTests
AUTH_CODE=d21pbzpUZXN0QDEyMzQ=
JMETER_HOME=/home/centos/apache-jmeter-5.2