CLOUD_NAME=edgeazstage3.int-az-us.webmethods-stage.io
LOGIN_URL=idm-az-us.softwareag-stage.cloud
TENANT_NAME=edgeazstage3
PROJECT_NAME=PerformanceTest
REMOTE_EDGE_SERVER_NAME=edgeorigin
PRODUCT_BUILD=ORIGIN_11.0.5.18
BASELINE_VERSION=11.0
TEST_CASE_FILE=Tests/Benchmark_testcase_All.csv
JMETER_HOME=/home/centos/apache-jmeter-5.5
#CHANGE THE TEST MASTER KEY BASED ON THE HYPERSCALER
#For AWS - ORIGIN_AWS_BPT
#For AZURE - ORIGIN_AZURE_BPT
TEST_MASTER_KEY=ORIGIN_AZURE_BPT
#DO NOT CHANGE BELOW LINE
RUN_ID=RUN_ID_VALUE
