name: bpt
on:
  workflow_dispatch:
env: 
  TENANT_USERNAME: ${{secrets.TENANT_USERNAME}}
  TENANT_PASSWORD: ${{secrets.TENANT_PASSWORD}}
  AUTH_CODE: ${{secrets.AUTH_CODE}}
jobs:
  setup:
    name: Checkout and fetch the baseline
    runs-on: vadorigin1

    steps:
    - name: Remove the existing files
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: |
         echo "Running on $RUNNER_CONTEXT"
         rm -rf *
    - uses: actions/checkout@v4
      with:
        path: main
    - name: Checkout PerfUtils
      uses: actions/checkout@v4
      with:
        repository: C2E/PerfUtil
        token: ${{ secrets.TOKEN }} # `GH_PAT` is a secret that contains your PAT
        ref: github_actions
        path: PerfUtil
    - name: Copy perf-origin and PerfUtil
      run: |
         cp -r main/* .
         cp -r PerfUtil/* .
         echo "Remove main and PerfUtil"
         rm -rf main
         rm -rf PerfUtil
         mkdir -p TEMP_DIRECTORY
         CURRENT_DIRECTORY=$PWD
         TEMP_DIRECTORY=$PWD/TEMP_DIRECTORY
         echo "CURRENT_DIRECTORY: $CURRENT_DIRECTORY"
         echo "TEMP_DIRECTORY: $TEMP_DIRECTORY"
         java -DPROPERTIES_FILE_PATH=$CURRENT_DIRECTORY/origin.properties -DCURRENT_DIRECTORY=$CURRENT_DIRECTORY/ -DTEMP_DIRECTORY=$TEMP_DIRECTORY/ -cp bpt_utils.jar perf.bpt.util.FetchBaseline
         RUN_ID=`java -cp bpt_utils.jar perf.bpt.metadata.TestMaster RUN_ID`
         echo "RUN_ID: $RUN_ID"
         sed -i "s*RUN_ID_VALUE*$RUN_ID*g" $CURRENT_DIRECTORY/origin.properties
    - uses: actions/upload-artifact@v3
      with:
        name: Baseline-results-CSV
        path: .    

    - name: Pull the docker image and push it to the cloud.
      run: |
         echo "pull the docker image and push it to the cloud."
         CURRENT_DIRECTORY=$PWD
         echo "CURRENT_DIRECTORY=$PWD"
         sh edge_docker_image.sh pull_edge_runtime_image $CURRENT_DIRECTORY

    - uses: actions/upload-artifact@v3
      with:
        name: edge-docker-image
        path: .

  edge-runtime-setup:
    name: Setup edge runtime
    needs: setup
    runs-on: CA3S-AWS-2

    steps:
    - name: Download the edge server and start the edge server
      env: 
        RUNNER_CONTEXT: ${{ toJson(runner) }} 
      run: |
         echo "Downloading the edge server."
         rm -rf *
    - uses: actions/download-artifact@v3
      with:
        name: edge-docker-image
        path: .
    - name: load the docker image
      run: |
         echo "Load the docker image."
         CURRENT_DIRECTORY=$PWD
         echo "CURRENT_DIRECTORY=$PWD"
         sh edge_docker_image.sh load_edge_runtime_image $CURRENT_DIRECTORY
         sh edge_docker_image.sh delete_existing_edge_runtime_from_tenant $TENANT_USERNAME $TENANT_PASSWORD
         sh edge_docker_image.sh configure_edge_runtime_on_tenant $TENANT_USERNAME $TENANT_PASSWORD
    
  execute:
    name: Execute the tests and compare with baseline
    needs: edge-runtime-setup
    runs-on: CA3S-AWS-3

    steps:
    - name: Remove the existing files
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: |
         echo "Running on $RUNNER_CONTEXT"
         rm -rf *
    - uses: actions/download-artifact@v3
      with:
        name: Baseline-results-CSV
        path: .
    - name: Execute the tests
      run: |
         CURRENT_DIRECTORY=$PWD
         TEMP_DIRECTORY=$PWD/TEMP_DIRECTORY
         echo "CURRENT_DIRECTORY: $CURRENT_DIRECTORY"
         echo "TEMP_DIRECTORY: $TEMP_DIRECTORY"
         sh test.sh $TEMP_DIRECTORY $TENANT_USERNAME $TENANT_PASSWORD
    - uses: actions/upload-artifact@v3
      with:
        name: Test-results-CSV
        path: .

  store:
    name: Store the results in Database
    needs: execute
    runs-on: vadorigin1
    steps:
      - name: Remove the existing files
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: |
             echo "Running on $RUNNER_CONTEXT"
             rm -rf *
      - uses: actions/download-artifact@v3
        with:
          name: Test-results-CSV
          path: .
      - name: Store the results in database
        run: |
             CURRENT_DIRECTORY=$PWD
             TEMP_DIRECTORY=$PWD/TEMP_DIRECTORY
             echo "CURRENT_DIRECTORY: $CURRENT_DIRECTORY"
             echo "TEMP_DIRECTORY: $TEMP_DIRECTORY"
             java -DPROPERTIES_FILE_PATH=$CURRENT_DIRECTORY/origin.properties -DRESULTS_FILE_PATH=$TEMP_DIRECTORY/TEST_RESULTS.csv -cp bpt_utils.jar perf.bpt.gitActionsProcessTestResults