name: bpt
on:
  workflow_dispatch:
env: 
  TENANT_USERNAME: ${{secrets.TENANT_USERNAME}}
  TENANT_PASSWORD: ${{secrets.TENANT_PASSWORD}}
  AUTH_CODE: ${{secrets.AUTH_CODE}}
jobs:
  setup:
    name: Checkout and fetch the baseline
    runs-on: vadorigin1

    steps:
    - name: Remove the existing files
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: |
         echo "Running on $RUNNER_CONTEXT"
         rm -rf *
    - uses: actions/checkout@v4
      with:
        path: main
    - name: Pull the docker image and push it to the cloud.
      run: |
         cp -r main/* .
         echo "pull the docker image and push it to the cloud."
         CURRENT_DIRECTORY=$PWD
         echo "CURRENT_DIRECTORY=$PWD"
         sh edge_docker_image.sh $CURRENT_DIRECTORY

    - uses: actions/upload-artifact@v3
      with:
        name: edge-docker-image
        path: .


    