name: origin-performance-bpt
run-name: ${{ inputs.id }} origin-performance-bpt
on:
  workflow_dispatch:
    inputs:
      id:
        required: true
env:
  BEARER: ${{ secrets.BEARER_MCSP_AZURE_TEST }}
  TENANT_API_KEY: ${{ secrets.APIKEY_MCSP_AZURE_TEST }}
jobs:
  setup:
    name: Checkout and fetch the baseline
    runs-on: [self-hosted, Linux, X64, vmperf]

    steps:
      - name: Remove the existing files
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: |
          echo "Running on $RUNNER_CONTEXT"
          rm -rf *
      - uses: actions/checkout@v4
        with:
          path: main
      - name: Checkout PerfUtils
        uses: actions/checkout@v4
        with:
          repository: ibm-webmethods/PerfUtil
          token: ${{ secrets.TOKEN }}
          ref: github_actions
          path: PerfUtil
      - name: Copy perf-origin and PerfUtil
        run: |
          cp -r main/* .
          cp -r PerfUtil/* .
          echo "Remove main and PerfUtil"
          rm -rf main
          rm -rf PerfUtil
          mkdir -p TEMP_DIRECTORY
          CURRENT_DIRECTORY=$PWD
          TEMP_DIRECTORY=$PWD/TEMP_DIRECTORY
          echo "CURRENT_DIRECTORY: $CURRENT_DIRECTORY"
          echo "TEMP_DIRECTORY: $TEMP_DIRECTORY"
          java -DPROPERTIES_FILE_PATH=$CURRENT_DIRECTORY/origin.properties -DCURRENT_DIRECTORY=$CURRENT_DIRECTORY/ -DTEMP_DIRECTORY=$TEMP_DIRECTORY/ -cp bpt_utils.jar perf.bpt.util.FetchBaseline
          RUN_ID=`java -cp bpt_utils.jar perf.bpt.metadata.TestMaster RUN_ID`
          echo "RUN_ID: $RUN_ID"
          sed -i "s*RUN_ID_VALUE*$RUN_ID*g" $CURRENT_DIRECTORY/origin.properties
      - uses: actions/upload-artifact@v4
        with:
          name: Baseline-results-CSV
          path: .

  execute:
    name: Execute the tests and compare with baseline
    needs: setup
    runs-on: [self-hosted, Linux, X64, vmperf]

    steps:
      - name: Validate required secrets
        run: |
          if [ -z "$BEARER" ]; then
            echo "BEARER secret is missing"
            exit 1
          fi
          if [ -z "$TENANT_API_KEY" ]; then
            echo "TENANT_API_KEY secret is missing"
            exit 1
          fi
      - name: Remove the existing files
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: |
          echo "Running on $RUNNER_CONTEXT"
          rm -rf *
      - uses: actions/download-artifact@v4
        with:
          name: Baseline-results-CSV
          path: .
      - name: Execute the tests
        run: |
          CURRENT_DIRECTORY=$PWD
          TEMP_DIRECTORY=$PWD/TEMP_DIRECTORY
          echo "CURRENT_DIRECTORY: $CURRENT_DIRECTORY"
          echo "TEMP_DIRECTORY: $TEMP_DIRECTORY"
          sh test.sh $TEMP_DIRECTORY $BEARER $TENANT_API_KEY
      - uses: actions/upload-artifact@v4
        with:
          name: Test-results-CSV
          path: .

  store:
    name: Store the results in Database
    needs: execute
    runs-on: [self-hosted, Linux, X64, vmperf]
    steps:
      - name: Remove the existing files
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: |
          echo "Running on $RUNNER_CONTEXT"
          rm -rf *
      - uses: actions/download-artifact@v4
        with:
          name: Test-results-CSV
          path: .
      - name: Store the results in database
        run: |
          CURRENT_DIRECTORY=$PWD
          TEMP_DIRECTORY=$PWD/TEMP_DIRECTORY
          echo "CURRENT_DIRECTORY: $CURRENT_DIRECTORY"
          echo "TEMP_DIRECTORY: $TEMP_DIRECTORY"
          java -DPROPERTIES_FILE_PATH=$CURRENT_DIRECTORY/origin.properties -DRESULTS_FILE_PATH=$TEMP_DIRECTORY/TEST_RESULTS.csv -cp bpt_utils.jar perf.bpt.gitActionsProcessTestResults
