name: example

on:
  workflow_dispatch:

jobs:
  job1:
    name: Job 1
    runs-on: vadorigin1

    steps:
    - name: Run a one-line script
    - uses: actions/checkout@v3
      with:
          repository: C2E/PerfUtil
          ref: origin
