name: example

on:
  workflow_dispatch:

jobs:
  job1:
    name: Job 1
    runs-on: vadorigin1

    steps:
    - uses: actions/checkout@v3
      with:
          token: ${{ secrets.TOKEN }}
          repository: C2E/PerfUtil
          ref: origin
    - name: Run a one-line script
      run: |
        echo Hello, world!
        sleep 15
        echo Goodbye!
        java --version
        java -cp bpt_utils.jar perf.bpt.metadata.TestMaster RUN_ID > temp.txt
        mkdir TEMP_DIRECTORY
