name: example

on:
  workflow_dispatch:

jobs:
  job1:
    name: Job 1
    runs-on: CA3S-AWS

    steps:
    - name: Sleep and Run
      run: |
        echo "Sleeping for 10"
        sleep 10

  job2:
    name: Job 2
    needs: job1
    runs-on: CA3S-AWS

    steps:
    - name: Dependant is Running
      run: |
        echo "Completed job 2, but triggering failure"
        java -version
