name: main

on:
  workflow_dispatch:

jobs:
  job1:
    name: Job 1
    runs-on: vadorigin1

    steps:
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run: |
         echo "Running on vadorigin1"
#        file="./origin.properties"
#        while IFS='=' read -r key value; do
#                echo "key: $key, value: $value"
#                sed -i "s*$key*$value*g" JMeterScripts/CreateEdgeServer.jmx
#        done < "$file"
#        /home/rdadmin/Softwares/apache-jmeter-5.4.1/bin/jmeter.sh -n -t JMeterScripts/CreateEdgeServer.jmx -Jthreads=1
  job2:
    name: Job 2
    needs: job1
    runs-on: CA3S-AWS

    steps:
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run: |
        sh test.sh
    - uses: actions/upload-artifact@v3
      with:
          name: jmeter-results-CSV
          path: TEMP_DIRECTORY/**/*.csv
  job3:
    name: Job 3
    needs: job2
    runs-on: vadorigin1
    steps:
    - name: Clean the directory
      run: rm -rf *
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: perf-origin

    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
        repository: C2E/PerfUtil
        token: ${{ secrets.TOKEN }} # `GH_PAT` is a secret that contains your PAT
        path: PerfUtil
    - name: Dependant is Running
      run: |
        cp -r PerfUtil/* .
        cp -r perf-origin/* .
        java -cp bpt_utils.jar perf.bpt.metadata.TestMaster RUN_ID > temp.txt
        mkdir TEMP_DIRECTORY
    - uses: actions/download-artifact@v2
      with:
        name: jmeter-results-CSV
    - name: Copy file
      run: |
        echo Copy File!
        cat temp.txt
        run_id=$(cat temp.txt)
        echo run id: $run_id
        cp *.csv TEMP_DIRECTORY/
        sh store_results.sh